steps:
  - uses: actions/checkout@v3
  - name: Cache choosenim
    id: cache-choosenim
    uses: actions/cache@v1
    with:
      path: ~/.choosenim
      key: ${{ runner.os }}-choosenim-stable
  - name: Cache nimble
    id: cache-nimble
    uses: actions/cache@v1
    with:
      path: ~/.nimble
      key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
  - uses: jiro4989/setup-nim-action@v1
    with:
      nim-version: '1.6.6' # default is 'stable'
  - run: nimble build -Y
  - run: nimble test -Y
